<a href="https://colab.research.google.com/github/truptiwagh13/ML-3-PR-codes/blob/main/implement_Frozen_Lake_using_SARSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#implement Frozen Lake using SARSA

import numpy as np
import gym

#Frozenlake-v0 gym environment
env = gym.make('FrozenLake-v1')

#parameters
epsilon = 0.9
total_episodes = 1000
max_steps = 100
alpha = 0.05
gamma = 0.95

#Initializing the Q-value
Q = np.zeros((env.observation_space.n, env.action_space.n))

#function to choose the next action woth episolon greedy
def choose_action(state):
  action = 0
  if np.random.uniform(0,1)<epsilon:
    action = env.action_space.sample()
  else:
    action = np.argmax(Q[state, :])
  return action

#Initializing the reward
reward = 0

#starting the SARSA_learning
for episode in range(total_episodes):
  t=0
  state1 = env.reset()
  action1 = choose_action(state1)

  while t < max_steps:
    #visualizing the training 


    #Getting the next state
    state2, reward, done, info = env.step(action1)

    action2 = choose_action(state2)

    Q[state1, action1] = Q[state1, action1] + alpha * (reward + gamma * Q[state2,action2] - Q[state1,action1])

    state1=state2
    action1=action2

    t += 1
    reward += 1

    if done:
      break

print("performance : ",reward/total_episodes)
print(Q)



/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


performance :  0.001
[[1.52349942e-04 1.75753724e-04 1.22024895e-04 1.17389168e-04]
 [6.49381516e-05 1.98963620e-04 1.31169721e-04 1.67421474e-04]
 [5.52488336e-04 5.60982653e-04 5.23811507e-04 1.34009235e-04]
 [5.58495408e-05 4.97698296e-05 1.49210760e-05 1.00747236e-04]
 [2.99060044e-04 2.67408388e-04 2.15266069e-04 1.06881088e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.92354816e-03 2.82459379e-03 1.95916320e-03 3.85754627e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.10154786e-04 7.92536560e-04 9.31785173e-04 8.72044179e-04]
 [2.48258020e-03 4.24454162e-03 3.88761691e-03 3.04864203e-03]
 [2.26223761e-02 1.68005253e-02 9.47218371e-03 5.07952409e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.47587281e-03 1.22339360e-02 1.54151162e-02 6.13656154e-03]
 [3.92950508e-02 1.88308621e-01 2.22845901e-01 1.22963516e-01]
 [0.00000000e+00 0.00000000e+00 0.